### ISSUE TITLE
Поправить сборку

### ISSUE THREAD

**Issue by coursar** [dispersion01/servlet-homework#2]
См. логи Travis CI:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/build/dispersion01/servlet-homework/src/main/java/ru/nikolaeva/file/FileConroller.java:[10,72] cannot find symbol
  symbol:   class MultipartFile
  location: class ru.nikolaeva.file.FileConroller
[ERROR] /home/travis/build/dispersion01/servlet-homework/src/main/java/ru/nikolaeva/file/FileConroller.java:[10,51] cannot find symbol
  symbol:   class RequestParam
  location: class ru.nikolaeva.file.FileConroller
[ERROR] /home/travis/build/dispersion01/servlet-homework/src/main/java/ru/nikolaeva/file/FileConroller.java:[9,6] cannot find symbol
  symbol:   class RequestMapping
  location: class ru.nikolaeva.file.FileConroller
[ERROR] /home/travis/build/dispersion01/servlet-homework/src/main/java/ru/nikolaeva/file/FileConroller.java:[9,53] cannot find symbol
  symbol:   variable RequestMethod
  location: class ru.nikolaeva.file.FileConroller
[ERROR] /home/travis/build/dispersion01/servlet-homework/src/main/java/ru/nikolaeva/file/FileConroller.java:[10,13] cannot find symbol
  symbol:   class ResponseBody
  location: class ru.nikolaeva.file.FileConroller
[INFO] 5 errors 
```

**Comment by dispersion01** [comment]
Ошибки исправила, только теперь он просит какой-то файл 'desFileName' 
[INFO] Total time:  2.944 s
[INFO] Finished at: 2019-05-19T15:09:15Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy (default) on project servlet-servlet-nikolaeva: Unable to parse configuration of mojo org.apache.maven.plugins:maven-dependency-plugin:3.1.1:copy for parameter desFileName: Cannot find 'desFileName' in class org.apache.maven.plugins.dependency.fromConfiguration.ArtifactItem -> [Help 1]

Не могу разобрать теперь, что делать дальше.

**Comment by coursar** [comment]
1. У вас неправильно сконфигурирован плагин, см #3 
2.  В этой задаче не нужно было использовать Spring или Commons (но даже если используете, используйте самые новые версии, а не старые - например, Spring у вас 4.x)
